export const Data = [
  {
    VideoTitle: "Advanced Web Orientation",
    date: "2022-03-11",
    id: 1,
    Recording: "WatchRecording",
    Instructor: "Awais Kamran",
  },
  {
    VideoTitle: "Advanced Web Class 1",
    date: "2022-03-09",
    id: 2,
    Recording: "WatchRecording",
    Instructor: "Awais Kamran",
  },
  {
    VideoTitle: "Advanced Web Class 2",
    date: "2022-03-26",
    id: 3,
    Recording: "WatchRecording",
    Instructor: "Awais Kamran",
  },
  {
    VideoTitle: "Advanced Web Class 3",
    date: "2022-03-27",
    id: 4,
    Recording: "WatchRecording",
    Instructor: "Awais Kamran",
  },
  {
    VideoTitle: "Advanced Web Class 4",
    date: "2022-04-02",
    id: 5,
    Recording: "WatchRecording",
    Instructor: "Awais Kamran",
  },
  {
    VideoTitle: "Advanced Web Class 5",
    date: "2022-04-03",
    id: 6,
    Recording: "WatchRecording",
    Instructor: "Awais Kamran",
  },
  {
    VideoTitle: "Advanced Web Class 6",
    date: "2022-04-09",
    id: 7,
    Recording: "WatchRecording",
    Instructor: "Awais Kamran",
  },
  {
    VideoTitle: "Advanced Web Class 7",
    date: "2022-04-17",
    id: 8,
    Recording: "WatchRecording",
    Instructor: "Awais Kamran",
  },
  {
    VideoTitle: "Advanced Web Class 8",
    date: "2022-03-23",
    id: 9,
    Recording: "WatchRecording",
    Instructor: "Awais Kamran",
  },
  {
    VideoTitle: "Advanced Web Class 9",
    date: "2022-03-24",
    id: 10,
    Recording: "WatchRecording",
    Instructor: "Awais Kamran",
  },
  {
    VideoTitle: "Advanced Web Class 10",
    date: "2022-03-27",
    id: 11,
    Recording: "WatchRecording",
    Instructor: "Awais Kamran",
  },
  {
    VideoTitle: "Advanced Web Class 11",
    date: "2022-03-28",
    id: 12,
    Recording: "WatchRecording",
    Instructor: "Awais Kamran",
  },
];
