export const data = [
  {
    id: 1,
    title: "student",
    name: "Fahad Mehmood",
    email: "fahadmehmood556@gmail.com",
  },
  {
    id: 2,
    title: "student",
    name: "Syed Shaheryar Ali",
    email: "k163969@nu.edu.pk",
  },
  {
    id: 3,
    title: "student",
    name: "Syed shahab shah",
    email: "shahabbukhari098@gmail.com",
  },
  {
    id: 4,
    title: "student",
    name: "Burhan Ali",
    email: "salmanali11186@gmail.com",
  },
  {
    id: 5,
    title: "student",
    name: "Waleed Ahmad",
    email: "rana.waleed123@gmail.com",
  },
  {
    id: 6,
    title: "student",
    name: "Afrasiab",
    email: "afrasiabkhan0@gmail.com",
  },
  {
    id: 7,
    title: "student",
    name: "Muhammad Aqeel Chughtai",
    email: "accesstoaqeel@gmail.com",
  },
  {
    id: 8,
    title: "student",
    name: "Aman Mohsin",
    email: "aman.mohsin@thedevnation.com",
  },
  {
    id: 9,
    title: "student",
    name: "Beenish",
    email: "beenishhina280@gmail.com",
  },
  {
    id: 10,
    title: "student",
    name: "HAMD BILAL TAHIR",
    email: "hamdbilaltahir100@gmail.com",
  },
  {
    id: 12,
    title: "student",
    name: "Muhammad Ukkasha",
    email: "ukkashameh@gmail.com",
  },
  {
    id: 13,
    title: "student",
    name: "Ahmed Raza",
    email: "ahmadrazach26@gmail.com",
  },
  {
    id: 14,
    title: "student",
    name: "Muhammad Awais",
    email: "awaiskhan3@gmail.com",
  },
  {
    id: 15,
    title: "student",
    name: "muhammad muneeb ejaz",
    email: "muhammad.muneeb.ejaz@gmail.com",
  },
  {
    id: 16,
    title: "student",
    name: "Mohtashim Ali",
    email: "mohtashima85@gmail.com",
  },
  {
    id: 17,
    title: "student",
    name: "Jamshed Iqbal",
    email: "jamshediqbal6155@gmail.com",
  },
  {
    id: 18,
    title: "student",
    name: "Ghulam Ali",
    email: "aali.ghulam1990@gmail.com",
  },
  {
    id: 19,
    title: "student",
    name: "Talha Malik",
    email: "talha.malik@thedevnation.com",
  },
  {
    id: 20,
    title: "student",
    name: "Mohsin Najam",
    email: "mohsinnajamm@gmail.com",
  },
  {
    id: 21,
    title: "student",
    name: "Arslan",
    email: "arslan.islam@thedevnation.com",
  },
  {
    id: 22,
    title: "student",
    name: "Abdulkarim Ahmed",
    email: "aaykay856@gmail.com",
  },
  {
    id: 23,
    title: "student",
    name: "Muhammad Awais",
    email: "fa19-bcs-072@cuiatk.edu.pk",
  },
  {
    id: 24,
    title: "student",
    name: "Muhammad Abdullah Habib",
    email: "sanawarshahzad61@gmail.com",
  },
  {
    id: 25,
    title: "student",
    name: "Huzaifa Mazhar",
    email: "malik.huzefa1@gmail.com",
  },
  {
    id: 26,
    title: "student",
    name: "Naveed Qadir",
    email: "naveedqadir8149@gmail.com",
  },
  {
    id: 27,
    title: "student",
    name: "Muhammad Ahmed",
    email: "winterfell551@gmail.com",
  },
  {
    id: 28,
    title: "student",
    name: "HAMD BILAL TAHIR",
    email: "hamd21@gmail.com",
  },
  {
    id: 29,
    title: "student",
    name: "Fahad Sajjad",
    email: "fahad61814mfan@gmail.com",
  },
  { id: 30, title: "student", name: "Raheel", email: "rab@testemail.com" },
  {
    id: 31,
    title: "student",
    name: "Tech Explorer",
    email: "waqasktk81@gmail.com",
  },
  {
    id: 32,
    title: "student",
    name: "Abdul Qudoos",
    email: "abdulahqudoosqudoos123@gmail.com",
  },
  {
    id: 33,
    title: "student",
    name: "Nasreen Khalid",
    email: "nasreen.1@live.com",
  },
  {
    id: 34,
    title: "student",
    name: "Shuja Ali Saleemuddin",
    email: "itsshuja1997@gmail.com",
  },
  {
    id: 35,
    title: "student",
    name: "Khizer Tanwir Ahmad",
    email: "khizer.tanwir@thedevnation.com",
  },
  {
    id: 36,
    title: "student",
    name: "Hamza Iftikhar",
    email: "hamza.iftikhar707@gmail.com",
  },
  {
    id: 37,
    title: "student",
    name: "Hamza khan",
    email: "m.hamzakhaan@gmail.com",
  },
  {
    id: 38,
    title: "student",
    name: "Sheza",
    email: "shezahussain733@gmail.com",
  },
  {
    id: 39,
    title: "student",
    name: "Abdul Haseeb",
    email: "mianhaseeeb302@gmail.com",
  },
  {
    id: 40,
    title: "student",
    name: "Abdul Jabbar",
    email: "mianhaseeeb302@gmail.com",
  },
];
