export const data = [
  {
    title: "HTML & CSS",
    duration: 2,
    topics: [
      "Introduction to the Web",
      "HTML & CSS",
      "Advanced CSS & Responsive Design",
      "Bootstrap",
    ],
  },
  {
    title: "Javascript & Advanced JS for Web",
    duration: 7,
    topics: [
      "Variables & Data Types",
      "IF-ELSE & Switch Statements",
      "Loops: FOR & WHILE",
      "Functions, Recursion",
      "Data Structures",
      "Object Oriented Programming",
      "DOM Manipulation",
      "Algorithmic Thinking",
      "Projects",
      "Whatsapp Clone",
      "Daily Task App",
      "Interactive Quiz App",
      "Weather Reporting App",
    ],
  },
  {
    title: "Databases",
    duration: 4,
    topics: [
      "Basics of Data Sciences",
      "Database Design",
      "SQL: Introduction & Advanced",
      "Second Normal Form",
      "Third Normal Form",
      "Design Consideration",
    ],
  },
  {
    title: "ReactJS - Beginners",
    duration: 4,
    topics: [
      "Introduction to ReactJS",
      "Rendering Elements",
      "Components & Props",
      "Handling Events, State & Lifecycle",
      "Conditional Rendering",
      "Lists & Keys",
      "Lifting State Up",
    ],
  },
  {
    title: "Advanced React.js",
    duration: 4,
    topics: [
      "React Composition",
      "React Hooks: useState, useEffect",
      "Advanced Hooks: useContext, useReducer",
      "React Optimization: useMemo, useCallback",
      "Testing in ReactJS with JEST",
      "Projects",
      "- LinkedIn Clone",
      "- Netflix Clone",
      "- Facebook Clone",
      "- Amazon Clone",
    ],
  },
  {
    title: "Career Development",
    duration: "Forever",
    topics: [
      "Resume & Profile Prep",
      "Effective Communication",
      "Mock Interviews",
      "Company Sessions",
      "Job Hunting",
      "Future Career Counseling",
      "Life-long membership",
      "Community of successful developers",
    ],
  },
];
